### ISSUE TITLE
Why it isn't updated for like 10 months? 

### ISSUE THREAD

**Issue by Dhizaes** [flathub/com.unity.UnityHub#102]
Exactly the caption. It installs 3.4.1 version of Unity Hub. I can see pull requests for version updates from bot. Is there something we need to do to get up-to-date version? If it is, why it isn't written to somewhere, like a README file.

**Comment by AlfishSoftware** [comment]
See https://github.com/flathub/com.unity.UnityHub/pull/73#issuecomment-1407370899

**Comment by wjt** [comment]
https://discourse.flathub.org/t/looking-for-someone-to-take-over-unity-hub-flatpak/5406 has some context. More committers have now arrived.
