### ISSUE TITLE
No audio?

### ISSUE THREAD

**Issue by 42Willow** [flathub/com.unity.UnityHub#103]
No audio plays..
![image](https://github.com/flathub/com.unity.UnityHub/assets/70784752/e291ca8f-cc84-4548-aa2e-6e27b1e661b9)

**Comment by wjt** [comment]
Audio playback works fine for me with editor 2022.3 and 2021.3. 

Can you give any more information about your environment? What distro are you using? Which version of pulseaudio/pipewire? Does sound work from other applications?

**Comment by 42Willow** [comment]
I was on Fedora 38 workstation, I've distro hopped over to tumbleweed now - and I'm not using Unity any more. So unless someone else has this issue I'm going to close it. Thanks for your help.
