### ISSUE TITLE
CDN URL oscillates between two versions of file

### ISSUE THREAD

**Issue by wjt** [flathub/com.unity.UnityHub#11]
Endless runs https://github.com/endlessm/flatpak-external-data-checker 4 times a day and I get emailed when it fails. Every day or so it fails for this repo:

```
BROKEN: UnityHubSetup.AppImage
 Has a new version:
  URL:    https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage
  SHA256: 695204884bd148cc5548af2227d31fc5a859904f17ca52563aa22dd20df87f3a
  Size:   63158410
```

Then within a few runs, it stops failing again. This file is the old version before I submitted 480c5f0962a89f6c6f2a307bc320be7a49bedff5. I can't reproduce this interactively, and I don't have enough logging on the Jenkins job that runs this script to get more info (e.g. HTTP headers) but the problem remains: the CDN may serve different files for the same URL, perhaps due to stale edge caches (though it's been almost 4 weeks now). I wonder what we can do about this – do we need to teach Flatpak that an extra-data URL may match any of a given list of sha256sums and sizes?

**Comment by refi64** [comment]
Hmm I'll probably just report this to them, because it kind of feels like trying to magically handle this on our end is going to result with a lot of weird inconsistencies + might throw too many complications into the patching.

**Comment by TingPing** [comment]
And even if extra-data support is extended you should expect users to be on not the latest `flatpak` release for a long time.

**Comment by wjt** [comment]
Very well!
