### ISSUE TITLE
Failed to install on Clear Linux

### ISSUE THREAD

**Issue by yerbestpal** [flathub/com.unity.UnityHub#12]
When running `flatpak install flathub com.unity.UnityHub` on Clear Linux (which has Flatpak and Flathub setup by default) I get the following error:

`error: Failed to install com.unity.UnityHub/x86_64/stable: Wrong size for extra data https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage`

**Comment by Eduardo555** [comment]
hey, yesterday I got the same problem, after the update I was able to perform the installation on fedora 30.

#6
