### ISSUE TITLE
Flatpak + sudo clarity.

### ISSUE THREAD

**Issue by communityus** [flathub/com.unity.UnityHub#16]
Super pleased this flatpak exists. The appimage can never find mono on Debian Jessie (SteamOS beta + clockwork)

I am new to flatpak, but is it normal to have to sudo as much as I am?

```
sudo apt install flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo flatpak install flathub com.unity.UnityHub
flatpak run com.unity.UnityHub
```

This has been the case to get Unity working for sometime now anything 2017.x (whenever they switched to one backend vs separate Linux backend.)

**Comment by TingPing** [comment]
You never have to use `sudo` with `flatpak` assuming your system has PolicyKit properly configured.

That said your usage is entirely fine.
