### ISSUE TITLE
UnityHubSetup.AppImage URL is broken

### ISSUE THREAD

**Issue by wjt** [flathub/com.unity.UnityHub#17]
https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage has disappeared:

```
wjt@camille:~$ http HEAD https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.AppImage
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 1
Date: Fri, 06 Sep 2019 10:40:35 GMT
Server: nginx/1.15.12
x-amz-error-code: NoSuchKey
x-amz-error-detail-Key: hub/prod/UnityHubSetup.AppImage
x-amz-error-message: The specified key does not exist.
x-amz-id-2: HYJ0KCP5TbQX2bqxmT00NoKL7T95FOnjtUC9TfNDGA/F/2rqRA8cqB5ohpoCHJU2UG9ow6rQwoI=
x-amz-request-id: C82572F0664B1E9D
```

I briefly explored the Unity website and forum and was unable to find an updated link.

The beta URL from #9 is live. I haven't tried running it, but maybe that could be a temporary workaround.

**Comment by refi64** [comment]
Updated with the new URL from [here](https://forum.unity.com/threads/unity-hub-v2-0-0-release.677485/#post-4936106).
