### ISSUE TITLE
Fatal Error! Failed to initialize unity graphics.

### ISSUE THREAD

**Issue by timvisee** [flathub/com.unity.UnityHub#20]
Since this week (it worked before), I'm getting the following error message when I try to load any Unity project from the hub:

![image](https://user-images.githubusercontent.com/856222/65675822-19b76b80-e04f-11e9-8938-648bf5d307e6.png)

I did update to the latest flatpak image using

```bash
flatpak update com.unity.UnityHub
```

I'm running Ubuntu 19.04 and did update my Nvidia driver to the latest available, being version 435.

I do not understand what is causing this, nor how I could debug this. Could this be an issue with the UnityHub flatpak image itself? If not, I'll be sure to close this issue.

**Comment by timvisee** [comment]
Reverting back to Nvidia 430 (because 435 caused other issues) did not solve this issue either.

**Comment by timvisee** [comment]
It just looks like it started working again. I don't know why, and didn't explicitly change anything. A package might have been updated to fix this.

Although the root issue hasn't really been found, I'll close this issue.

**Comment by refi64** [comment]
I'm guessing it was a runtime issue... At minimum, nothing about it seemed
reproducible from over here.

**Comment by timvisee** [comment]
Probably, yes. I'm glad it got fixed somehow.

I didn't know how to debug the flatpak package, but I'll attempt to do that next time to gain better insight on what is happening.
