### ISSUE TITLE
Wrong size for extra data

### ISSUE THREAD

**Issue by fummie** [flathub/com.unity.UnityHub#23]
Getting "Unable to install "Unity Hub": Wrong size for extra data https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage" error, when trying to install

**Comment by refi64** [comment]
Could you try again? Could've been a fluke, that's happened before with their CDN.

**Comment by scde** [comment]
Hey same issue here I think it is because you didn't publish the newest [commit (for version 2.1.3)](https://github.com/flathub/com.unity.UnityHub/commit/30928b38851497ec84e1dd9fb56d49c1edab95e4) yet. At least not on flathub.

Thanks in advance and have a nice day.

**Comment by refi64** [comment]
OOF sorry about that, looks like the commit didn't build for some reason.
However, it should be pushed now:
https://flathub.org/builds/#/builders/32/builds/10768

I'll leave this open to make sure it's working over there as well.

**Comment by fummie** [comment]
thx, working now
