### ISSUE TITLE
Sandbox issues with 2.3.0

### ISSUE THREAD

**Issue by FakeShemp** [flathub/com.unity.UnityHub#30]
```flatpak run  com.unity.UnityHub```
```
[3:0309/093328.144401:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

It runs fine with ```flatpak run  com.unity.UnityHub  --no-sandbox```.

**Comment by FakeShemp** [comment]
I tried to switch the app to use `org.electronjs.Electron2.BaseApp` instead and run it with `zypak-wrapper`. But even then it has sandbox permission failures.

**Comment by refi64** [comment]
Of course the one time I don't test the automated extra-data merge it
breaks, will fix today.

**Comment by refi64** [comment]
Weirdly enough...it works perfectly over here even without Zypak. I cleared out every application data folder I could find and tried running it, but I can't get the sandbox to fail at all. The sandbox binary isn't even there... I can't even find any references to the sandbox in the extracted resources file.

**Comment by FakeShemp** [comment]
Weird. I tried on another computer and get the same result. I will do some tests.
```
$ flatpak run com.unity.UnityHub 
[3:0309/200036.049590:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
/app/bin/start-unityhub: line 21:     3 Trace/breakpoint trap   (core dumped) UNITY_DATADIR=$XDG_DATA_HOME TMPDIR=$XDG_CACHE_HOME /app/extra/unityhub "$@"
```
```
$ flatpak --version 
Flatpak 1.6.2
```

**Comment by refi64** [comment]
Let me just uninstall Unity Hub completely and reinstall

**Comment by refi64** [comment]
Nope still working over here :thinking: Out of curiosity, what distro is this running on?

**Comment by FakeShemp** [comment]
Ubuntu 19.10

**Comment by FakeShemp** [comment]
Tried on a third computer and still have sandbox issues. I will investigate more.

**Comment by refi64** [comment]
Well desperate times call for desperate measures, guess I'll spin up a Ubuntu VM and see what happens...

**Comment by FakeShemp** [comment]
On an unrelated note, I think `eula.txt` has been removed from the appimage.

I deleted all settings and reinstalled. zenity starts as it should but can't find the EULA. But after accepting, the app fails at sandboxing again.

**Comment by FakeShemp** [comment]
Also tried on a Fedora VM, where everything works as it should. I'm stumped but think it's an Ubuntu issue.

**Comment by FakeShemp** [comment]
Looking into the Unity app, the init script looks like this:
```
# !/usr/bin/env bash

# Uncomment for debugging purposes:
# set -eux

UNPRIVILEGED_USERNS_ENABLED=$(cat /proc/sys/kernel/unprivileged_userns_clone 2>/dev/null)
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec "$SCRIPT_DIR/unityhub-bin" "$([[ $UNPRIVILEGED_USERNS_ENABLED == '' || $UNPRIVILEGED_USERNS_ENABLED == 0 ]] && echo '--no-sandbox')" "$@"
```
I think this should make it run with `--no-sandbox` for most users, but on my system `UNPRIVILEGED_USERNS_ENABLED` is set to `1`, which I'm guessing makes it launch with sandboxing.

**Comment by refi64** [comment]
Thanks for the sleuthing! I can definitely reproduce this now.

**Comment by refi64** [comment]
Looks like this will need some Zypak tweaks, meanwhile I'll push out a version that uses `--no-sandbox` which should fix it for you!

**Comment by refi64** [comment]
Okay actually I just needed to make a stub chrome-sandbox executable, changes are already pushed out.
