### ISSUE TITLE
Unity Hub links do not trigger install

### ISSUE THREAD

**Issue by jelle619** [flathub/com.unity.UnityHub#33]
Unity provides Unity Hub links on their [archival site](https://unity3d.com/get-unity/download/archive) with downloads and Unity Hub links. Since Unity does not provide downloads for Linux through this, using the latter remains the only easy way for Linux users to install previous versions of Unity on their computer. However, this functionality is broken.

For example, this link is supposed to open up the Unity Hub and install version Unity 2018.4.20: unityhub://2018.4.20f1/008688490035. However, in the case of the Flatpak, it opens the Unity Hub (like it should) but does not prompt the installation of said version, thus rendering the link useless.

In the case of the official AppImage version Unity provides, Unity Hub links can be opened through the terminal. This worked for me in my testing:

```
./unityhubappimage unityhub://2018.4.20f1/008688490035
```

The only workaround at the moment is to install the version you want through the AppImage and moving over the config files to the Flatpak app. It's quite messy to do, but it gets the job done for now.

Personally, I consider this feature a must, since games or other Unity projects can take a long time to make. In this time period, the project often isn't updated to a newer version of Unity and, thus, anyone who wishes to participate in such a projects would have to install an older version of Unity, which isn't possible as of yet with the Unity Hub Flatpak.

**Comment by refi64** [comment]
Fixed in 1cbd2561dadd9b40b786ad7b48790ea956ba3266, you can view the build progress [here](https://flathub.org/builds/#/builders/32/builds/19935).

**Comment by jelle619** [comment]
Still appears to be broken.
