### ISSUE TITLE
Crashes on open ?

### ISSUE THREAD

**Issue by theotheroracle** [flathub/com.unity.UnityHub#35]
Fedora 32 Workstation
```
ellie@lana-pula-silvia ~> flatpak run com.unity.UnityHub
Gtk-Message: 11:25:23.660: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:25:23.660: Failed to load module "pk-gtk-module"
Gtk-Message: 11:25:23.660: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:25:23.660: Failed to load module "pk-gtk-module"
libgcrypt state transition Fatal-Error => Fatal-Error denied
libgcrypt state transition Fatal-Error => Fatal-Error denied
fatal error in libgcrypt, file ../../src/visibility.c, line 1361, function gcry_create_nonce: called in non-operational state
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
/app/bin/start-unityhub: line 21:     3 Aborted                 (core dumped) UNITY_DATADIR=$XDG_DATA_HOME TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/unityhub-bin "$@"
ellie@lana-pula-silvia ~ [SIGABRT]> 
```

**Comment by Splizzlah** [comment]
This just happened to me using Beta version 2020, Im lazy dont wanna get exact version number. Not that im lazy ive spent numerous hours, days, weeks. Learning linux and chrome os. I had Unity3d working very well! ive got some videos ive taken even fps working flawless on a chromebook atom5x. So i got excited downloaded bunch of material makers, model programs that go along with unity 3d.  I got bored got emulator played some psp for few days for a break. I got back to unity3d and the performance was bad. ( I am writting a story to show exactly my experience here) So i got rid of play store entirely to see if it was android, nope performance low still, well I paniced and powerwashed, did a install of linux updated it , made sure i had all the despondencys and what have you. Installed Unity3d through www.flatpak.org ( all programs work flawless with this org) Decided to try beta , it crashed, I have to experiment if it was the multithread flag i activated as i recently just turned it on for first time. I am installing the stable build 31.4 2019 and it should be done so im gonna test that with multi thread flag for chrome os to see if my performance is boosted, Ill let you know in 5 mins, even tho you probaly dont even own a chromebook hahaha. Keep in mind i had this program working just fine yesterday or the day before, one of those days

**Comment by Splizzlah** [comment]
Ok so the program is loading up just fine, actually alot faster then before, and the install went a lot faster. I am wondering if there is a bug during install and thats why it freezes up and takes along time, and other times it doesn't take as long. 
IDK GUYS! performance is low again, I might have to dip from this project and go cry in a corner for a week and come back to see if there is a fix.

**Comment by refi64** [comment]
Whoops, this got buried in my email in guess. This looks a lot like https://github.com/microsoft/vscode/issues/99725 which itself [was a libsecret bug](https://gitlab.gnome.org/GNOME/libsecret/-/issues/48). The latest shared modules has a fix, so I'll be pushing that out now which should fix this.

**Comment by Splizzlah** [comment]
Really? I gave up on Chrome OS all together, and used GalliumOS which
resolved my issue. haha ( what really pissed me off the most , was how UFPS
is selling version 2 when i bought version 1 and never got to use it

**Comment by refi64** [comment]
Gonna assume this was the libsecret issue.
