### ISSUE TITLE
libgcrypt error on UnityHub

### ISSUE THREAD

**Issue by jeteokeeffe** [flathub/com.unity.UnityHub#39]
Flatpak 1.6.3
   Static hostname: laptop
         Icon name: computer-convertible
           Chassis: convertible
        Machine ID: 0413f9d569054f39bf89faaceb1e822b
           Boot ID: 14944528cdae435c8a6f055f53aa5dfa
  Operating System: Fedora 32 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:32
            Kernel: Linux 5.6.19-300.fc32.x86_64
      Architecture: x86-64

Fully patched Fedora 32 running Wayland.
`flatpak info com.unity.UnityHub`
Unity Hub - Real-time game engine

          ID: com.unity.UnityHub
         Ref: app/com.unity.UnityHub/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.3.2
     License: LicenseRef-proprietary
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 451.8 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 76e77db455ad8ee6793e5005b75cc13a656c9734dcdcd18ca1101db9e4bff7f2
      Parent: dd08988f32fbaf385134acdd8a16a4d567d7afae00531f42423cf8197359025e
     Subject: Added git support for unity teams and UPM, closes #21 (f9f2920d)
        Date: 2020-06-04 22:32:27 +0000

I run this command
`flatpak run com.unity.UnityHub `

This is the output
Gtk-Message: 11:21:02.484: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:21:02.484: Failed to load module "pk-gtk-module"
Gtk-Message: 11:21:02.484: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:21:02.484: Failed to load module "pk-gtk-module"
libgcrypt state transition Fatal-Error => Fatal-Error denied
fatal error in libgcrypt, file ../../src/visibility.c, line 1361, function gcry_create_nonce: called in non-operational state
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
/app/bin/start-unityhub: line 21:     3 Aborted                 (core dumped) UNITY_DATADIR=$XDG_DATA_HOME TMPDIR=$XDG_CACHE_HOME zypak-wrapper /app/extra/unityhub-bin "$@"

**Comment by refi64** [comment]
Dup of #35
