### ISSUE TITLE
Can't build to Android

### ISSUE THREAD

**Issue by bastianilso** [flathub/com.unity.UnityHub#4]
Hi,

I am trying to build to Android from Unity inside the UnityHub flatpak but:

1. "Build and Run" cannot find any Android device connected to it.
1. "Build" with Internal or Gradle does not work, as it fails to invoke java from the android sdk installed at /opt/android-sdk

EDIT: Building with Gradle seems to work (sorry for the misinfo). However, I still have issues with Build and Run.

**Comment by refi64** [comment]
Hmm, maybe Build and Run just has issues finding adb to boot? We could probably just add a custom shell script wrapper that uses flatpak-spawn like with VS Code...

The Java will be a bit odd, I'm not entirely sure how many Java binaries from the SDK it wants, given that it maybe wants the same Java?

**Comment by FakeShemp** [comment]
Is it possible to make this work if I install Android Studio from Flathub?
