### ISSUE TITLE
Input issues Fedora 32

### ISSUE THREAD

**Issue by djotaku** [flathub/com.unity.UnityHub#49]
Unity Hub 2.4.2 (same issue whether launching Unity Hub from the official Unity AppImage or from Unity Flathub package)

Unity editor version 2020.1.11f1 (currently downloading 2020.2.2f1 to see if that fixes things)

Desktop environment: KDE/Plasma 5

Here are the issues:

    Within the editor I cannot use my mouse scroll wheel to scroll any part of the UI. For example, if a game object has 6 C# scripts on it and a few things like colliders. So if I want to go from the top to the bottom there, I have to move the scroll bar with a left click - there is no scroll wheel support
    With the new input system if I go into game mode, I can't use the keyboard keys to move around. Same files work just fine in Windows to move with WASD setup.

**Comment by refi64** [comment]
Unfortunately, our ability to work around bugs in Hub or Unity itself is very limited, and if this is reproducible with the AppImage it's not something we can really control.
