### ISSUE TITLE
Unity won't download

### ISSUE THREAD

**Issue by Bonekiller99** [flathub/com.unity.UnityHub#50]
I am trying to download UnityHub via flatpak (AKA Flathub) and when I try to install it, it says there's an error. I tried other apps and those worked but for some reason, Unity didn't want to download. I also tried executing the UnityHub.AppImage, but that didn't work either. When I try executing it through terminal, it says "no such file or directory". Any thoughts? I'm using the Raspberry Pi OS on a Raspberry Pi 4 Model B.

**Comment by springbov** [comment]
I have a couple ideas. For me I am running on an x86_64 processor and not a raspberry pi (an arm based processor). I don't know if unity has any arm binaries or not. If there is not, then there isn't a good way to run unity on your raspberry pi.

The second idea is I was having a similar issue with the app image where it would not download unity itself. unity hub would launch but I couldn't download anything. I resolved that by changing where unity hub thought the temp directory was. Something like `TMPDIR=~/.tmp ~/AppImages/UnityHub.AppImage`

My hunch is that there just isn't an arm build for unity itself.

**Comment by refi64** [comment]
Indeed, the application is x64-only.

**Comment by V-BoltStudios** [comment]
Sorry for the long reply. If I get the Raspberry Pi 64bit OS on my Pi, will it work then?

**Comment by hfiguiere** [comment]
No. This is x86_64 only (ie standard PC)

RaspberryPi is aarch64.
