### ISSUE TITLE
Even when appstream updated, no results found for flatpak install flathub com.unity.UnityHub.

### ISSUE THREAD

**Issue by musicalcomposer** [flathub/com.unity.UnityHub#54]

**Comment by BrainBlasted** [comment]
I also can't seem to find Unity Hub using the GNOME Software currently.

**Comment by refi64** [comment]
I can't seem to reproduce this at all, odd. Is there anything about these systems you could describe that could help me narrow things down?

**Comment by refi64** [comment]
So it turns out the image URLs had gone bad, I just updated them. Anyone want to try again with the latest appdata?

**Comment by wjt** [comment]
Works with GNOME Software today, 2½ years later.
