### ISSUE TITLE
Trying to install UnityHub gives an error

### ISSUE THREAD

**Issue by TrafficLight42** [flathub/com.unity.UnityHub#56]
Trying to install UnityHub from flatpak with `flatpak install com.unity.UnityHub` gives this error:

`error: Failed to install com.unity.UnityHub: Wrong size for extra data https://public-cdn.cloud.unity3d.com/hub/prod/UnityHub.AppImage`

I've restarted and tried again, and attempted to clear the cash (which there didn't seem to be any) but it still doesn't work :(

**Comment by leonidussaks** [comment]
+1

**Comment by TrafficLight42** [comment]
It now installs successfully without errors. No idea what changed...
