### ISSUE TITLE
Update to 3.0 or remove it from Flathub

### ISSUE THREAD

**Issue by SnowKaya** [flathub/com.unity.UnityHub#65]
As we all know, Unity Hub 2.x.x is now deprecated an unsupported. New versions from the Unity Engine will only be distributed on the ver. 3 of the Hub, and this version is only available via repository.

Unless there are negotiations with Unity for them distributing the Hub per .appimage or flatpak, it's better remove it from Flathub.

**Comment by alex285** [comment]
that's basically https://github.com/flathub/com.unity.UnityHub/issues/64

**Comment by refi64** [comment]
#64
