### ISSUE TITLE
Build unity games as a flatpak

### ISSUE THREAD

**Issue by Dangerdonny** [flathub/com.unity.UnityHub#66]
Since we have the option to install unity hub as a flatpak, then are we also able to distribute unity games as a flatpak? If so, how would we go about doing so?

**Comment by Pyrofanis** [comment]
as far as i see it this is a community run project based on the now discontinued appimage unity hub.

i guess it is possible to package your game in flatpak form or any other considering the tree dir type unity uses to build linux games but you have to have knowledge building it yourself 

till now the only engine i know that it supports some kind of cross distro package manager is game makers studio with the capability of exporting your game as an appimage

**Comment by Dangerdonny** [comment]
Thanks!
