### ISSUE TITLE
Store "Open in Unity" button does not work with Unity Flatpak

### ISSUE THREAD

**Issue by jperezCurso** [flathub/com.unity.UnityHub#92]
Hi.
I've been using Unity Flatpak on OpenSuse Leap 15.4 for a couple of days and everything works fine, until I try to move assets from the Unity Asset Store to the project.
When I press the "Open in Unity" button on the store, it does nothing.

**Comment by cassidyjames** [comment]
@jperezCurso were you able to solve this? I'm seeing something similar to this and #67 (Unity Asset Store on the web tries to open a `com.unity3d.kharma:content/` link which is not handled), so I wonder if we should re-open this or if I should file a new issue.

**Comment by norappmob** [comment]
I haven't tried it again in a while, so I don't know if it will work or not. I'm sorry.
